//test error

void func(int x) {
  return x;
}

int main() {
  func(2);
  return 0;
}
